<?php
/*
    CoreManager, PHP Front End for ArcEmu, MaNGOS, and TrinityCore
    Copyright (C) 2010  CoreManager Project

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Unused Language Pack Sections
*/

// ----- REPAIR.PHP -----
/*$GLOBALS['lang_repair'] = array
(
  'repair_optimize' => 'Repair / Optimize Tables',
  'repair' => 'Repair',
  'optimize' => 'Optimize',
  'start' => 'Start',
  'repair_finished' => 'Repair / Optimization Finished',
  'no_table_selected' => 'No Table(s) Selected',
  'table_name' => 'Table Name',
  'status' => 'Status',
  'num_records' => 'Number of Records',
  'tables' => 'Tables',
  'select_tables' => 'Select Tables the operation to be performed on.',
  'repair_error' => 'Error',
);*/


// ----- BACKUP.PHP -----
/*$GLOBALS['lang_backup'] = array
(
  'backup_options' => 'Backup Options',
  'select_option' => 'Select backup opton',
  'save' => 'Save',
  'load' => 'Load',
  'to_from' => 'To/From',
  'web_backup' => 'WebServer Saved',
  'local_file' => 'Local File',
  'acc_on_file' => 'Account on a File',
  'enter_acc_name' => 'Enter Account ID you wish to Load',
  'backup_acc' => 'BackUp Accounts',
  'go' => 'Go',
  'save_table_struc_backup' => 'Save table(s) structural backup in addition to data backup',
  'select_file' => 'Select File',
  'max_file_size' => 'Maximum Upload Filesize is',
  'use_ftp_for_large_files' => 'For Larger volumes you can upload your backup files of any size<br />via FTP directly to your backup directory',
  'upload' => 'Upload',
  'upload_sql_file_only' => 'You may only upload .sql or .qbquery files.',
  'upload_err_write_permission' => 'Couldn\'t Upload File<br />Check the directory permissions for',
  'file_not_found' => 'File Not Found!',
  'file_write_err' => 'Couldn\'t Write to a File!',
  'backup_finished' => 'Backup Finished Successfully',
  'select_backup' => 'Select Backup File',
  'file_loaded' => 'File Loaded and',
  'que_executed' => 'Queries Executed Successfully',
  'tables_to_save' => 'The following tables will be Saved',
  'save_all_realms' => 'Save data from all Realms'
);*/

// ----- CLEANUP.PHP -----
/*$GLOBALS['lang_cleanup'] = array
(
  'cleanup_options' => 'CleanUp Options',
  'clean_chars' => 'Clean Characters',
  'char_level' => 'Character Level',
  'tot_play_time' => 'Total Play Time (sec)',
  'clean_acc' => 'Clean Accounts',
  'last_login_time' => 'Last Login (Y:M:D)',
  'failed_logins' => 'Failed Loggins',
  'banned' => 'Banned',
  'locked' => 'Muted',
  'chars_in_acc' => 'Characters in Account',
  'clean_guilds' => 'Clean Guilds',
  'chars_in_guild' => 'Characters in Guild',
  'run_cleanup' => 'Run CleanUp',
  'chars_id' => 'Character(s) id(s)',
  'tot_of' => 'Total of',
  'acc_ids' => 'Account(s) id(s)',
  'guilds_id' => 'Guild(s) id(s)',
  'no_guilds_del' => 'No Guilds deleted!',
  'total' => 'Total',
  'guilds_deleted' => 'Guild(s) deleted!',
  'no_acc_chars_deleted' => 'No Accounts/Characters deleted!<br />Permission Error?',
  'accs_deleted' => 'Account(s) deleted!',
  'chars_deleted' => 'Character(s) deleted!',
  'back_cleaning' => 'Back Cleaning',
  'clean_db' => 'Clean Database',
  'arenateams_deleted' => 'Arena Team(s) deleted!',
  'no_arenateams_del' => 'No Arena Team(s) deleted!'
);*/


// -----RUN_PATCH.PHP -----
/*$GLOBALS['lang_run_patch'] = array
(
  'err_in_line' => 'SQL syntax error in query number ',
  'run_sql_file_only' => 'You may only run .sql or .qbquery files.',
  'file_not_found' => 'File Not Found!',
  'select_sql_file' => 'Select SQL File to Open',
  'max_filesize' => 'Maximum Filesize',
  'open' => 'Open',
  'run_rules' => 'The following query(s) will be executed.<br />Make sure each query line ends with \'&#059;\' sign.',
  'select_db' => 'Select DB to be used by Default',
  'run_sql' => 'Run SQL',
  'query_executed' => 'SQL Query(s) Executed Successfully.',
  'no_query_found' => 'Zero Result Returned / Non queries Found.',
  'run_patch' => 'Run SQL Patch'
);*/


// ----- SSH.PHP -----
/*$GLOBALS['lang_ssh'] = array
(
  'server_offline' => 'SSH/Telnet Server appears to be Offline!',
  'config_server_properly' => 'Make sure you have configured your SSH/Telnet server properly, and it is currently online.',
);*/


// ----- TELE.PHP -----
/*$GLOBALS['lang_tele'] = array
(
  'add_new' => 'Add New',
  'add_new_tele' => 'Add New Recall Location',
  'delete_tele' => 'Delete',
  'edit_tele' => 'Edit Teleport Location',
  'error_updating' => 'Error Updating',
  'id' => 'ID',
  'loc_id' => 'Location ID',
  'loc_name' => 'Location Name',
  'map' => 'Map',
  'name' => 'Name',
  'on_map' => 'On Map ID',
  'orientation' => 'Orientation',
  'position_x' => 'Position X',
  'position_y' => 'Position Y',
  'position_z' => 'Position Z',
  'search_results' => 'Search Results',
  'tele_locations' => 'Recall Locations',
  'tele_updated' => 'Location Updated',
  'teleports' => 'Recalls',
  'tot_locations' => 'Total Recall locations',
  'update_tele' => 'Update Location',
  'x' => 'X',
  'y' => 'Y',
  'z' => 'Z',
);*/


// ----- WORLDBROADCAST.PHP -----
/*$GLOBALS['lang_wbm'] = array
(
  'add_new' => 'Add New',
  'add_new_wbm' => 'Add New World Broadcast Message',
  'delete_wbm' => 'Delete',
  'edit_wbm' => 'Edit World Broadcast Message',
  'error_updating' => 'Error Updating',
  'entry' => 'Entry',
  'text' => 'Text',
  'percent' => 'Cut-off',
  'search_results' => 'Search Results',
  'wbm' => 'World Broadcast Messages',
  'wbm_updated' => 'Message Updated',
  'messages' => 'All Messages',
  'tot_messages' => 'Total World Broadcast Messages',
  'update_wbm' => 'Update Message'
);*/


// ----- COMMAND.PHP -----
/*$GLOBALS['lang_command'] = array
(
  'command_list' => 'Available Commands',
  'level0' => 'Player',
  'level1' => 'Moderator',
  'level2' => 'Game Master',
  'level3' => 'Bug Tracker',
  'level4' => 'Administrator',
  'level5' => 'Sys OP',
  'level6' => 'Unknown',
  'command' => 'Command',
  'syntax' => 'Syntax',
  'description' => 'Description',
  'change_level' => 'Change Checked Command(s) Level',
  'save' => 'Save',
);*/


// ----- ITEM.PHP -----
/*$GLOBALS['lang_item_edit'] = array
(
  'search_item' => 'Search for Item(s)',
  'model_id' => 'Model Id',
  'all' => 'All',
  'search' => '+ Search +',
  'add_new_item' => 'Add New Item',
  'tot_items_in_db' => 'Total items in DB',
  'new_search' => 'New Search',
  'items_found' => 'Items Found',
  'item_not_found' => 'Item NOT Found in DB',
  'search_results' => 'Search Results',
  'edit_item' => 'Edit Item',
  'search_items' => 'Lookup Items',
  'update' => 'Save Item to Database',
  'export_sql' => 'Save as SQL Script',
  'item_id' => 'Item ID',
  'err_adding_item' => 'Error Adding Item',
  'err_no_field_updated' => 'Non of the fields updated.',
  'del_item' => 'Delete Item',
  'general_tab' => 'General',
  'additional_tab' => 'Extra',
  'stats_tab' => 'Stats',
  'damage_tab' => 'Damage',
  'spell_tab' => 'Spells',
  'req_tab' => 'Req.',
  'general' => 'General',
  'entry' => 'Entry',
  'entry_desc' => 'This is the unique ID of an Item.',
  'display_id' => 'Display ID',
  'display_id_desc' => 'This is the Model ID of an Item.',
  'req_level' => 'Req. Level',
  'req_level_desc' => 'Minimum level to use/equip this item.',
  'item_level' => 'Item Level',
  'item_level_desc' => 'Item base level.',
  'names' => 'Names',
  'item_name' => 'Item Name',
  'item_name_desc' => 'Item Name',
  'description' => 'Description',
  'description_desc' => 'Brief description of this item, appears in orange at the bottom of an item label ingame.',
  'script_name' => 'ScriptName',
  'script_name_desc' => 'Here can be added script entries defined in core code.',
  'class' => 'Class',
  'class_desc' => 'Defines the class of an item.',
  'type' => 'Type',
  'subclass' => 'Subclass',
  'subclass_desc' => 'Defines the subclass of an item. Notice: The subclass must be related to Item Class. Some Classes do not have any subclasses.',
  'quality' => 'Quality',
  'quality_desc' => 'The overall quality of an item.',
  'inv_type' => 'Inv. Type',
  'inv_type_desc' => 'Where this item can be equipped.',
  'flags' => 'Flags',
  'flags_desc' => 'TODO: Add proper description.',
  'item_set' => 'Item Set',
  'item_set_desc' => 'The ID of an item set this item belongs to.',
  'bonding' => 'Bonding',
  'bonding_desc' => 'Item Bonding type.',
  'start_quest' => 'Start Quest',
  'start_quest_desc' => 'ID of a quest that this item starts.',
  'short_rules_desc' => '* Moving your mouse over the field name will show you short field description.<br />* Make sure you properly filled all the fields and you are not trying to insert new item using existing entry.',
  'vendor' => 'Vendor',
  'buy_count' => 'BuyCount',
  'buy_count_desc' => 'Size of the stack in which the item is sold by vendors.',
  'buy_price' => 'BuyPrice',
  'buy_price_desc' => 'Price (in copper) of a stack of #BuyCount items.',
  'sell_price' => 'SellPrice',
  'sell_price_desc' => 'How much a vendor will buy this item for from the player. If omitted, the item will sell for nothing (No sell price).',
  'container' => 'Container',
  'bag_family' => 'BagFamily',
  'bag_family_desc' => 'Type of Container.',
  'bag_slots' => 'Container Slots',
  'bag_slots_desc' => 'Number of slots that this bag holds.',
  'materials' => 'Materials',
  'material' => 'Material',
  'material_desc' => 'The material the item is made of. Affects the sound that the item makes when moved.',
  'consumables' => 'Consumables',
  'none' => 'None',
  'metal' => 'Metal',
  'wood' => 'Wood',
  'liquid' => 'Liquid',
  'jewelry' => 'Jewelry',
  'chain' => 'Chain',
  'plate' => 'Plate',
  'cloth' => 'Cloth',
  'leather' => 'Leather',
  'page_material' => 'Page Material',
  'page_material_desc' => 'The background of the page window (and to some extent the font).',
  'parchment' => 'Parchment',
  'stone' => 'Stone',
  'marble' => 'Marble',
  'silver' => 'Silver',
  'bronze' => 'Bronze',
  'max_durability' => 'Max Durability',
  'max_durability_desc' => 'Durability of an item.',
  'other' => 'Other',
  'max_count' => 'MaxCount',
  'max_count_desc' => 'Maximum number of this item that the player can have. ( 0:not limited, 1:Unique)',
  'stackable' => 'Stackable',
  'stackable_desc' => 'The amount of this item that a player can carry in the same slot.',
  'page_text' => 'PageText',
  'page_text_desc' => 'ID of a TEXT in the item_text table, the text for a book or letter for example. The item will have a magnifying glass cursor ingame and will show the pagetext upon rightclicking the item.',
  'RandomProperty' => 'Random Property',
  'RandomProperty_desc' => 'Random enchantment entry.',
  'lang_id' => 'Language ID',
  'lang_id_desc' => 'Language that this item is written in.',
  'sheath' => 'Sheath',
  'sheath_desc' => 'How the weapon is put away (to the side, on the back, etc.).',
  'lock_id' => 'Lock Id',
  'lock_id_desc' => 'TODO: Add description.',
  'disenchant_id' => 'Disenchant ID',
  'disenchant_id_desc' => 'Refers to disenchant_loot_template.entry.',
  'area' => 'Zone',
  'area_desc' => 'Area ID only in which the item is usable',
  'map' => 'Map',
  'map_desc' => 'Map ID only in which the item is usable',
  'stats' => 'Stats',
  'stat_type' => 'Stat type',
  'stat_type_desc' => 'Character stat which will be changed if the item is equipped.',
  'stat_value' => 'Stat value',
  'stat_value_desc' => 'This value will be added to the stat (or removed if negative).',
  'resis_armor' => 'Resistance / Armor',
  'armor_desc' => 'Armor for this item.',
  'block_desc' => 'Shield\'s chance to block an attack.',
  'res_holy_desc' => 'Holy resistance for this item.',
  'res_fire_desc' => 'Fire resistance for this item.',
  'res_nature_desc' => 'Nature resistance for this item.',
  'res_frost_desc' => 'Frost resistance for this item.',
  'res_shadow_desc' => 'Shadow resistance for this item.',
  'res_arcane_desc' => 'Arcane resistance for this item.',
  'weapon_properties' => 'Weapon properties',
  'delay' => 'Delay',
  'delay_desc' => 'Time in milliseconds between hits.',
  'ranged_mod' => 'Ranged',
  'ranged_mod_desc' => 'TODO: Add description.',
  'ammo_type' => 'Ammo Type',
  'ammo_type_desc' => 'The type of ammunition this weapon requires.',
  'weapon_damage' => 'Weapon Damage',
  'damage_type' => 'Damage Type',
  'damage_type_desc' => 'Type of the Damage will be dealt by this item.',
  'dmg_min_max' => 'Damage : Min - Max',
  'dmg_min_max_desc' => 'Minimal and maximal damage values.',
  'spell_id' => 'Spell Id',
  'spell_id_desc' => 'Refers to Spell.dbc index.',
  'spell_trigger' => 'Spell trigger',
  'spell_trigger_desc' => 'The action triggers this spell.',
  'spell_charges' => 'Spell Charges',
  'spell_charges_desc' => 'Number of charges for this spell.(0: infinite, -X: item is expendable, +X: item is kept when all charges are spent).',
  'spell_cooldown' => 'Spell Cooldown',
  'spell_cooldown_desc' => 'Spell cooldown time in milliseconds.',
  'spell_category' => 'Spell Category',
  'spell_category_desc' => 'Spell Category.',
  'spell_category_cooldown' => 'Spell Category Cooldown',
  'spell_category_cooldown_desc' => 'Global cooldown for entire category.',
  'allow_class' => 'Allowable Class',
  'allow_class_desc' => 'Mask for character classes that can use this item.',
  'allow_race' => 'Allowable Race',
  'allow_race_desc' => 'Mask for races which can use this item.',
  'req_skill' => 'Required Skill',
  'req_skill_desc' => 'Skill required to use this item.',
  'req_skill_rank' => 'Required Skill Rank',
  'req_skill_rank_desc' => 'Minimum proficiency in skill to use this item.',
  'req_spell' => 'Required Spell',
  'req_spell_desc' => 'Player must know this spell to use the item.',
  'req_honor_rank' => 'Required Honor Rank',
  'req_honor_rank_desc' => 'The PvP Honor rank required to use this item.',
  'req_rep_faction' => 'Required Faction',
  'req_rep_faction_desc' => 'Faction id (from Faction.dbc) for which a minimum rank is required to equip/use the item.',
  'req_rep_rank' => 'Required Faction Standing',
  'req_rep_rank_desc' => 'Minimum required rank for the faction entered in RequiredReputationFaction.',
  'req_city_rank' => 'Required City Rank',
  'req_city_rank_desc' => 'Required City Rank.',
  'hated' => 'Hated',
  'hostile' => 'Hostile',
  'unfriendly' => 'Unfriendly',
  'neutral' => 'Neutral',
  'friendly' => 'Friendly',
  'honored' => 'Honored',
  'reverted' => 'Reverted',
  'exalted' => 'Exalted',
  'sock_tab' => 'Sockets',
  'req_skill_disenchant' => 'Req. Disenchant Skill',
  'req_skill_disenchant_desc' => 'Disenchant Skill Required in order to disenchant this item.',
  'RandomSuffix' => 'Random Suffix',
  'RandomSuffix_desc' => 'Random enchantment suffix entry.',
  'unk0' => 'unk0',
  'unk0_desc' => 'TODO:',
  'totem_category' => 'Totem Type',
  'totem_category_desc' => 'Type of the totem. Linked to TotemCategory.dbc',
  'socket_color' => 'Socket Color',
  'socket_color_desc' => 'Color of this Socket.',
  'socket_content' => 'Socket Content',
  'socket_content_desc' => 'Jem socketed into this socket',
  'socket_bonus' => 'Socket Bonus',
  'socket_bonus_desc' => 'Bonus upon socketting. Linked to SpellItemEnchantment.dbc',
  'gem_properties' => 'Gem Poperties',
  'gem_properties_desc' => 'Linked to GemProperties.dbc',
  'custom_search' => 'Custom Filter',
  'info' => 'Info.',
  'dropped_by' => 'Item Dropped by',
  'top_x' => '(top 5)',
  'sold_by' => 'Item Sold by',
  'limit_x' => '(limited to 5 results)',
  'mob_name' => 'Name',
  'mob_minlevel' => 'Min Level',
  'mob_maxlevel' => 'Max Level',
  'norm10_drop_chance' => 'Normal 10&nbsp;Man',
  'norm25_drop_chance' => 'Normal 25&nbsp;Man',
  'hero10_drop_chance' => 'Heroic 10&nbsp;Man',
  'hero25_drop_chance' => 'Heroic 25&nbsp;Man',
  'mob_quest_drop_chance' => 'Quest Drop Chance',
  'involved_in_quests' => 'Required for Quest(s)',
  'reward_from_quest' => 'Reward from Quest(s)',
  'disenchant_tab' => 'Disenchant',
  'disenchant_templ' => 'Disenchant Template',
  'add_items_to_templ' => 'Add Item to Template',
  'loot_item_id' => 'Item ID',
  'loot_item_id_desc' => 'ID of the item you wish to be added.',
  'loot_drop_chance' => 'Drop Chance',
  'loot_drop_chance_desc' => 'Item Drop chance',
  'loot_quest_drop_chance' => 'Quest Drop Chance',
  'loot_quest_drop_chance_desc' => 'Quest Drop chance',
  'min_count' => 'Minimum Count',
  'min_count_desc' => 'Minimum number of stack size on drop.',
  'max_count' => 'Maximum Count',
  'max_count_desc' => 'Maximum number of stack size on drop.',
  'add_item_to_loot' => 'Add item to Loot Template',
  'drop_chance' => 'Drop Chance',
  'quest_drop_chance' => 'Quest Drop Chance',
  'armor_dmg_mod' => 'Armor Damage Modifier',
  'armor_dmg_mod_desc' => 'TODO:',
  'ppm_rate' => 'ppmRate',
  'ppm_rate_desc' => 'Number of proc per minute',
  'item_spell' => 'Item Spell',
  'freeforall' => 'Free for all',
  'freeforall_desc' => 'Free for all loot flag.',
  'lootcondition' => 'Loot condition',
  'lootcondition_desc' => 'Loot condition flag',
  'condition_value1' => 'Condition Value 1',
  'condition_value1_desc' => 'Condition Value 1 flag',
  'condition_value2' => 'Condition Value 2',
  'condition_value2_desc' => 'Condition Value 2 flag',
);*/

// ----- CREATURE.PHP -----
/*$GLOBALS['lang_creature'] = array
(
  'none' => 'None',
  'custom' => 'Custom',
  'gossip' => 'Gossip',
  'quest_giver' => 'Quest Giver',
  'vendor' => 'Vendor',
  'taxi' => 'Taxi',
  'trainer' => 'Trainer',
  'spirit_healer' => 'Spirit Healer',
  'guard' => 'Guard',
  'inn_keeper' => 'Inn Keeper',
  'banker' => 'Banker',
  'retitioner' => 'Retitioner',
  'tabard_vendor' => 'Tabard Vendor',
  'battlemaster' => 'Battlemaster',
  'auctioneer' => 'Auctioneer',
  'stable_master' => 'Stable Master',
  'armorer' => 'Armorer',
  'normal' => 'Normal',
  'elite' => 'Elite',
  'rare_elite' => 'Rare Elite',
  'world_boss' => 'World Boss',
  'rare' => 'Rare',
  'search_template' => 'Search Creature Prototypes',
  'select' => 'Select',
  'other' => 'Other',
  'beast' => 'Beast',
  'dragonkin' => 'Dragonkin',
  'demon' => 'Demon',
  'elemental' => 'Elemental',
  'giant' => 'Giant',
  'undead' => 'Undead',
  'humanoid' => 'Humanoid',
  'critter' => 'Critter',
  'mechanical' => 'Mechanical',
  'not_specified' => 'Not Specified',
  'class' => 'Class',
  'mounts' => 'Mounts',
  'trade_skill' => 'Trade Skill',
  'pets' => 'Pets',
  'wolf' => 'Wolf',
  'cat' => 'Cat',
  'spider' => 'Spider',
  'bear' => 'Bear',
  'boar' => 'Boar',
  'crocolisk' => 'Crocolisk',
  'carrion_bird' => 'Carrion Bird',
  'crab' => 'Crab',
  'gorilla' => 'Gorilla',
  'raptor' => 'Raptor',
  'tallstrider' => 'Tallstrider',
  'felhunter' => 'Felhunter',
  'voidwalker' => 'Voidwalker',
  'succubus' => 'Succubus',
  'doomguard' => 'Doomguard',
  'scorpid' => 'Scorpid',
  'turtle' => 'Turtle',
  'scorpid' => 'Scorpid',
  'imp' => 'Imp',
  'bat' => 'Bat',
  'hyena' => 'Hyena',
  'owl' => 'Owl',
  'wind_serpent' => 'Wind Serpent',
  'search' => 'Search',
  'new_search' => 'New Search',
  'add_new' => 'Add New Creature',
  'tot_creature_templ' => 'Total Creature Prototypes',
  'tot_found' => 'Total Found',
  'general' => 'General',
  'stats' => 'Stats',
  'models' => 'Models',
  'additional' => 'Additional',
  'entry' => 'Entry',
  'entry_desc' => 'Creature\'s id.',
  'name' => 'Name',
  'name_desc' => 'Base name of the creature.',
  'faction' => 'Faction',
  'sub_name' => 'SubName',
  'sub_name_desc' => 'Subname of the creature.',
  'script_name' => 'Script Name',
  'script_name_desc' => 'Script\'s name creature uses.',
  'basic_status' => 'Basic Status',
  'level' => 'Level',
  'min_level' => 'Minimum Level',
  'min_level_desc' => 'Creature\'s minimum level. Spawned creature have level in range from minlevel to maxlevel.',
  'max_level' => 'Maximum Level',
  'max_level_desc' => 'Creature\'s maximum level. Spawned creature have level in range from minlevel to maxlevel.',
  'rank' => 'Rank',
  'rank_desc' => 'Creature\'s honor rank.',
  'health' => 'Health',
  'min_health' => 'Min Health',
  'min_health_desc' => 'Maximum creature\'s health points for creature level equal minlevel. Spawned creature have health in linear proportion to level position in range minlevel - maxlevel.',
  'max_health' => 'Max Health',
  'max_health_desc' => 'Maximum creature\'s health points for creature level equal maxlevel. Spawned creature have health in linear proportion to level position in range minlevel - maxlevel.',
  'min_mana' => 'Mana',
  'min_mana_desc' => 'Creature\'s mana points for creature level equal minlevel. Spawned creature have mana in linear proportion to level position in range minlevel - maxlevel.',
  'max_mana' => 'Max Mana',
  'max_mana_desc' => 'Maximum creature\'s mana points for creature level equal minlevel. Spawned creature have mana in linear proportion to level position in range minlevel - maxlevel.',
  'family' => 'Family',
  'family_desc' => 'Creature\'s family type.',
  'type' => 'Type',
  'type_desc' => 'Creature type.',
  'npc_flag' => 'NPC Flag',
  'npc_flag_desc' => 'This is way to cliet know how info you see if you clic(RMB) on NPC if is vendor if is auction in fact is menu how you see Is what type of NPC it is.',
  'trainer_type' => 'Trainer Type',
  'trainer_type_desc' => 'If NPC flag is set to Trainer this flag will specify its type.',
  'loot' => 'Loot',
  'loot_id' => 'Loot Id',
  'loot_id_desc' => 'Refered to field loot_template.entry.',
  'skin_loot' => 'Skin Loot',
  'skin_loot_desc' => 'Type of loot if creature is skinned.',
  'pickpocket_loot' => 'Pickpocket Loot',
  'pickpocket_loot_desc' => 'Refered to field pickpocketing_loot_template.entry.',
  'min_gold' => 'Min Gold',
  'min_gold_desc' => 'Minimum gold drop.',
  'max_gold' => 'Max Gold',
  'max_gold_desc' => 'Maximum gold drop. 0 = creature don\'t drop any gold.',
  'basic_status' => 'Basic Status',
  'armor' => 'Armor',
  'armor_desc' => 'Creature\'s armor.',
  'speed' => 'Speed',
  'speed_desc' => 'Creature\'s speed. Use float values in 0<<3 range.',
  'size' => 'Size',
  'size_desc' => 'Creature model size 1 = 100%. Float  0<<3 range.',
  'damage' => 'Damage',
  'min_damage' => 'Min Damage',
  'min_damage_desc' => 'Creature\'s minimum melee damage.',
  'max_damage' => 'Max Damage',
  'max_damage_desc' => 'Creature\'s maximum melee damage.',
  'attack_power' => 'Attack Power',
  'attack_power_desc' => 'Creature\'s melee attack power.',
  'min_range_dmg' => 'Min Ranged Damage',
  'min_range_dmg_desc' => 'Minimum creature\'s range damage.',
  'max_range_dmg' => 'Max Ranged Damage',
  'max_range_dmg_desc' => 'Maximum creature\'s range damage.',
  'ranged_attack_power' => 'Ranged Attack Power',
  'ranged_attack_power_desc' => 'Creature\'s ranged attack power.',
  'attack_time' => 'Attack Time',
  'attack_time_desc' => 'Time between each creature\'s melee attacks (ms).',
  'range_attack_time' => 'Range Attack Time',
  'range_attack_time_desc' => 'Time between each creature\'s range attacks (ms).',
  'combat_reach' => 'Combat Reach',
  'combat_reach_desc' => 'The distance from the creature can hit you.',
  'bounding_radius' => 'Bounding Radius',
  'bounding_radius_desc' => 'Radius from what player can be attacked.',
  'spells' => 'Spells',
  'spell' => 'Spell',
  'spell_desc' => 'Creature\'s spell.',
  'resistances' => 'Resistances',
  'resis_holy' => 'Holy Resitance',
  'resis_holy_desc' => 'Holy Resitance.',
  'resis_fire' => 'Fire Resitance',
  'resis_fire_desc' => 'Fire Resitance.',
  'resis_nature' => 'Nature Resitance',
  'resis_nature_desc' => 'Nature Resitance.',
  'resis_frost' => 'Frost Resitance',
  'resis_frost_desc' => 'Frost Resitance.',
  'resis_shadow' => 'Shadow Resitance',
  'resis_shadow_desc' => 'Shadow Resitance.',
  'resis_arcane' => 'Arcane Resitance',
  'resis_arcane_desc' => 'Arcane Resitance.',
  'models' => 'Models',
  'scripts' => 'Scripts',
  'ai_name' => 'AIName',
  'ai_name_desc' => 'Name of the AI function creature uses.',
  'movement_type' => 'MovementType',
  'movement_type_desc' => 'TODO.',
  'class' => 'class',
  'class_desc' => 'Creature\'s class, like character.class field. Used for check in case npcflag include trainer flag (16) and trainer_type == TRAINER_TYPE_CLASS or TRAINER_TYPE_PETS.',
  'race' => 'Race',
  'race_desc' => 'Creature\'s race, like character.race field. Used for check in case npcflag include trainer flag (16) and trainer_type == TRAINER_TYPE_MOUNTS.',
  'trainer_spell' => 'Trainer Spell',
  'trainer_spell_desc' => 'Spell ID. Used for check in case npcflag include trainer flag (16) and trainer_type == TRAINER_TYPE_TRADESKILLS. Player must known trainer_spell to start training.',
  'inhabit_type' => 'Inhabit Type',
  'inhabit_type_desc' => 'Movment type.<br />0 - not used<br />1 - can walk (or fly above ground)<br />2 - can swim (or fly above water)<br />3 (= 1 | 2) - can walk and swim (and fly)',
  'walk' => 'Walk',
  'swim' => 'Swim',
  'both' => 'Both',
  'flags_extra' => 'Flags Extra',
  'flags_extra_desc' => 'TODO:',
  'flags' => 'Flags',
  'flags_desc' => 'TODO:',
  'dynamic_flags' => 'Dynamic Flags',
  'dynamic_flags_desc' => 'TODO:',
  'flag_1' => 'Flag 1',
  'flag_1_desc' => 'Mobgroup: If you attack one of this group each mob in the group will aggro you.',
  'save_to_db' => 'Save to Database',
  'save_to_script' => 'Save as SQL Script',
  'lookup_creature' => 'Lookup Creature',
  'quests' => 'Quests',
  'vendor' => 'Vendor',
  'trainer' => 'Trainer',
  'creature_swapned' => 'This Creature is spawned a total of',
  'times' => 'time(s)',
  'del_creature' => 'Delete Creature',
  'del_spawns' => 'Delete Spawns',
  'loot_tmpl_id' => 'Loot template ID',
  'drop_chance' => 'Drop chance',
  'quest_drop_chance' => 'Quest Drop chance',
  'start_quests' => 'Start Quests',
  'ends_quests' => 'Ends Quests',
  'sells' => 'Sells',
  'unlimited' => 'Unlimited',
  'count' => 'Count',
  'trains' => 'Trains',
  'spell_id' => 'Spell ID',
  'cost' => 'Cost',
  'req_skill' => 'Required Skill',
  'req_skill_lvl' => 'Required Skill level',
  'req_level' => 'Required Level',
  'creature_template' => 'Creature Proto ID',
  'all_related_data' => 'All related data will be erased as well.',
  'add_new_mob_templ' => 'Add new creature Template',
  'add_new_success' => 'Creature Successfully Added',
  'edit_mob_templ' => 'Edit Creature Prototype',
  'err_adding_new' => 'Error Adding New Creature',
  'err_no_fields_updated' => 'Non of the fields updated.',
  'search_creatures' => 'Search Creatures',
  'custom_search' => 'Custom Filter',
  'pickpocketloot_tmpl_id' => 'Pickpocket Loot Template ID',
  'skinning_loot_tmpl_id' => 'Skinning Loot Template ID',
  'add_items_to_templ' => 'Add Item to Template',
  'loot_item_id' => 'Item ID',
  'loot_item_id_desc' => 'ID of the item you wish to be added.',
  'loot_drop_chance' => 'Drop Chance',
  'loot_drop_chance_desc' => 'Item Drop chance',
  'loot_quest_drop_chance' => 'Quest Drop Chance',
  'loot_quest_drop_chance_desc' => 'Quest Drop chance',
  'min_count' => 'Minimum Count',
  'min_count_desc' => 'Minimum number of stack size on drop.',
  'max_count' => 'Maximum Count',
  'max_count_desc' => 'Maximum number of stack size on drop.',
  'add_item_to_loot' => 'Add item to Loot Template',
  'drop_chance' => 'Drop Chance',
  'add_ends_quests' => 'Add Quest ends by this NPC',
  'add_starts_quests' => 'Add Quest starts by this NPC',
  'quest_id' => 'Quest ID',
  'quest_id_desc' => 'ID of the quest.',
  'add_items_to_vendor' => 'Add item to Vendor',
  'vendor_item_id' => 'Item Id',
  'vendor_item_id_desc' => 'Id of item you wish to add.',
  'vendor_max_count' => 'Maximum Count',
  'vendor_max_count_desc' => 'Maximim number of items can be soled.',
  'vendor_incrtime' => 'Increase Time',
  'vendor_incrtime_desc' => 'Time before this item can be soled again.',
  'vendor_extended_cost' => 'Extended Cost',
  'vendor_extended_cost_desc' => 'Honor point required to buy. Linked to ItemExtendedCost.dbc',
  'train_spell_id' => 'Spell Id',
  'train_spell_id_desc' => 'Id of the spell you like this trainer to train.',
  'add_spell_to_trainer' => 'Add Spell to Trainer',
  'train_cost' => 'Cost',
  'train_cost_desc' => 'Cost in cooper of this skill.',
  'req_skill' => 'Req. Skill',
  'req_skill_desc' => 'Skill id required to learn this spell.',
  'req_skill_value' => 'Req. Skill Value',
  'req_skill_value_desc' => 'Skill level required to learn this spell.',
  'req_level' => 'Req. Level',
  'req_level_desc' => 'Character level required to learn this spell.',
  'check_to_delete' => '* Check checkbox next to item to remove from template.',
  'search_results' => 'Search Results',
  'RacialLeader' => 'Boss',
  'RacialLeader_desc' => 'Set to 1 if the creature is a Boss',
  'dmgschool' => 'Damage School',
  'dmgschool_desc' => 'The school of damage will be used by this mob',
  'freeforall' => 'Free for all',
  'freeforall_desc' => 'Free for all loot flag.',
  'lootcondition' => 'Loot condition',
  'lootcondition_desc' => 'Loot condition flag',
  'condition_value1' => 'Condition Value 1',
  'condition_value1_desc' => 'Condition Value 1 flag',
  'condition_value2' => 'Condition Value 2',
  'condition_value2_desc' => 'Condition Value 2 flag',
  'modelid_A' => 'Model ID Male 1',
  'modelid_A_desc' => 'Model ID Male 1',
  'modelid_A2' => 'Model ID Male 2',
  'modelid_A2_desc' => 'Model ID Male 2',
  'modelid_H' => 'Model ID Female 1',
  'modelid_H_desc' => 'Model ID Female 1',
  'modelid_H2' => 'Model ID Female 2',
  'modelid_H2_desc' => 'Model ID Female 2',
  'faction_A' => 'Faction',
  'faction_A_desc' => 'The faction if the creature.',
  'faction_H' => 'Faction (Horde)',
  'faction_H_desc' => 'The faction if the creature is on the horde side.',
  'RegenHealth' => 'Regenerate Health',
  'equipment' => 'Equipment',
  'equip_slot' => 'Equip Slot',
  'equip_slot1_desc' => 'Offset to the real slot used',
  'equip_slot2_desc' => 'Offset to the real slot used',
  'equip_slot3_desc' => 'Offset to the real slot used',
  'equip_model' => 'Equip Model',
  'equip_model1_desc' => 'This is the model of the equipment used in right hand.',
  'equip_model2_desc' => 'This is the model of the equipment used in right hand.',
  'equip_model3_desc' => 'This is the model of the equipment used in distance slot.',
  'equip_info' => 'Equip Info',
  'equip_info1_desc' => 'This field controls both the animation, the way the equiped item hits and the sound it makes.',
  'equip_info2_desc' => 'This field controls both the animation, the way the equiped item hits and the sound it makes',
  'equip_info3_desc' => 'This field controls both the animation, the way the equiped item hits and the sound it makes',
  'heroic' => 'Heroic Spawn ID',
  'heroic_desc' => 'A heroic id is used when a creature has a different template for instances in normal and heroic mode. The one with the heroic_entry is the one used in the normal mode. A zero values means, this template is used for normal and heroic mode, or only heroic mode, if another creature point with its heroic_entry to this creature.',
  'locales' => 'Localisation',
  'unit_flags' => 'Unit flags',
);*/
  
// ----- VENDOR.PHP -----
/*$GLOBALS['lang_vendor'] = array
(
  'sells' => 'Sells',
  'restrictions' => 'Restrictions',
  'search_vendors' => 'Search Vendors',
  'add_item' => 'Add New Item',
  'edit_item' => 'Edit Item',
  'editing_item' => 'Editing Item',
  'del_item' => 'Delete Selected Item(s)',
  'tot_vendors' => 'Total Vendors',
  'del_creature' => 'Delete Vendor',
  'vendorid' => 'Vendor ID',
  'add_new_vendor' => 'Add New Vendor',
  'edit_vendor' => 'Edit Vendor',
  'racemask' => 'Race Mask',
  'racemaskdesc' => 'TODO',
  'reqrepfaction' => '... in Faction',
  'reqrepfactiondesc' => 'TODO',
  'reqrepfactionvalue' => 'Required Reputation',
  'reqrepfactionvaluedesc' => 'TODO',
  'canbuyattextid' => 'Can Buy Text ID',
  'canbuyattextiddesc' => 'TODO',
  'cannotbuyattextid' => 'Cannot Buy Text ID',
  'cannotbuyattextiddesc' => 'TODO',
  'editlabel' => 'Edit',
  'viewlabel' => 'View',
  'save' => 'Save Item',
  'search_creatures' => 'Search Vendors',
  'entry' => 'Entry',
  'item' => 'Item ID',
  'quantity' => 'Quantity',
  'maxquantity' => 'Max Quantity',
  'inctime' => 'Restock Time',
  'extcost' => 'Extended Cost',
  'limit' => 'Limit Results',
  'search_results' => 'Search Results',
  'save_to_db' => 'Save to Database',
  'save_to_script' => 'Save as SQL Script',
  'lookup_vendor' => 'Lookup Vendor',
  'tot_found' => 'Total Found',
  'new_search' => 'New Search',
  'search' => 'Search',
  'custom_search' => 'Custom Filter',
  'all_related_data' => 'All related data will be erased as well.',
);*/

// ----- GAME_OBJECT.PHP -----
/*$GLOBALS['lang_game_object'] = array
(
  'unknown' => 'Unknown',
  'custom_search' => 'Custom Filter',
  'search' => '+ Search +',
  'add_new' => 'Add New',
  'tot_go_templ' => 'Total Game Object Templates',
  'search_template' => 'Search Game Object Template',
  'select' => 'Select',
  'new_search' => 'New Search',
  'tot_found' => 'Total Templates Found',
  'add_new_go_templ' => 'Add New Game Object Template',
  'edit_go_templ' => 'Edit Game Object Template',
  'err_adding_new' => 'Error Adding New Game Object Template',
  'err_no_fields_updated' => 'Error: No Fields Updated',
  'search_go' => 'Search Game Objects',
  'general' => 'General',
  'save_to_db' => 'Save to DB',
  'save_to_script' => 'Save to Script',
  'lookup_go' => 'Lookup GO',
  'DOOR' => 'DOOR',
  'BUTTON' => 'BUTTON',
  'QUESTGIVER' => 'QUESTGIVER',
  'CHEST' => 'CHEST',
  'BINDER' => 'BINDER',
  'GENERIC' => 'GENERIC',
  'TRAP' => 'TRAP',
  'CHAIR' => 'CHAIR',
  'SPELL_FOCUS' => 'SPELL_FOCUS',
  'TEXT' => 'TEXT',
  'GOOBER' => 'GOOBER',
  'TRANSPORT' => 'TRANSPORT',
  'AREADAMAGE' => 'AREADAMAGE',
  'CAMERA' => 'CAMERA',
  'MAP_OBJECT' => 'MAP_OBJECT',
  'MO_TRANSPORT' => 'MO_TRANSPORT',
  'DUEL_FLAG' => 'DUEL_FLAG',
  'FISHING_BOBBER' => 'FISHING_BOBBER',
  'RITUAL' => 'RITUAL',
  'MAILBOX' => 'MAILBOX',
  'AUCTIONHOUSE' => 'AUCTIONHOUSE',
  'GUARDPOST' => 'GUARDPOST',
  'SPELLCASTER' => 'SPELLCASTER',
  'MEETING_STONE' => 'MEETING_STONE',
  'BG_Flag' => 'BG_Flag',
  'FISHING_HOLE' => 'FISHING_HOLE',
  'FLAGDROP' => 'FLAGDROP',
  'CUSTOM_TELEPORTER' => 'CUSTOM_TELEPORTER',
  'LOTTERY_KIOSK' => 'LOTTERY_KIOSK',
  'CAPTURE_POINT' => 'CAPTURE_POINT',
  'AURA_GENERATOR' => 'AURA_GENERATOR',
  'DUNGEON_DIFFICULTY' => 'DUNGEON_DIFFICULTY',
  'general' => 'General',
  'name' => 'Name',
  'name_desc' => 'Object\'s name.',
  'entry' => 'Entry',
  'entry_desc' => 'Unique GO identifier value',
  'displayId' => 'Display Id',
  'displayId_desc' => 'Graphic model\'s id sent to the client.',
  'faction' => 'Faction',
  'faction_desc' => 'Object\'s faction, if any.',
  'flags' => 'Flags',
  'flags_desc' => 'TODO:',
  'type' => 'Type',
  'type_desc' => 'Game Object\'s type',
  'script_name' => 'ScriptName',
  'ScriptName_desc' => 'Script\'s name GO uses.',
  'size' => 'Size',
  'size_desc' => 'Object\'s size must be set because graphic models can be resample.',
  'tmpl_not_found' => 'Template not Found',
  'del_go' => 'Delete GO',
  'del_spawns' => 'Delete Spawns',
  'loot' => 'Loot',
  'quests' => 'Quests',
  'loot_tmpl_id' => 'Loot Template',
  'drop_chance' => 'Drop Chance',
  'quest_drop_chance' => 'Quest Drop Chance',
  'add_items_to_templ' => 'Add Items to Template',
  'loot_item_id' => 'Loot template ID',
  'loot_item_id_desc' => 'ID of the item you wish to be added.',
  'loot_drop_chance' => 'Drop Chance',
  'loot_drop_chance_desc' => 'Item Drop chance',
  'loot_quest_drop_chance' => 'Quest Drop Chance',
  'loot_quest_drop_chance_desc' => 'Quest Drop chance',
  'min_count' => 'Minimum Count',
  'min_count_desc' => 'Minimum number of stack size on drop.',
  'max_count' => 'Maximum Count',
  'max_count_desc' => 'Maximum number of stack size on drop.',
  'check_to_delete' => '* Check checkbox next to item to remove from template.',
  'add_starts_quests' => 'Add Quest starts by this GO',
  'quest_id' => 'Quest ID',
  'quest_id_desc' => 'ID of the quest.',
  'start_quests' => 'Start Quests',
  'ends_quests' => 'Ends Quests',
  'add_ends_quests' => 'Add Quest ends by this GO',
  'go_swapned' => 'This Game Object spawned total of',
  'times' => 'times',
  'go_template' => 'Game Object Template',
  'all_related_data' => 'Along with all related data.',
  'freeforall' => 'Free for all',
  'freeforall_desc' => 'Free for all loot flag.',
  'lootcondition' => 'Loot condition',
  'lootcondition_desc' => 'Loot condition flag',
  'condition_value1' => 'Condition Value 1',
  'condition_value1_desc' => 'Condition Value 1 flag',
  'condition_value2' => 'Condition Value 2',
  'condition_value2_desc' => 'Condition Value 2 flag',
  'datas' => 'Additional Datas',
  'data' => 'Data',
  'data_desc' => 'Data fields specific for different type field values. Each type has unique fields.<br />For more informaton visit https://svn.mangosproject.org/trac /MaNGOS/wiki/Database /gameobject_template'
);*/

// ----- EVENTS.PHP -----
/*$GLOBALS['lang_events'] = array
(
  'total' => 'Total',
  'start' => 'First Starting Time',
  'occur' => 'Occurance<br /><small>days/hours</small>',
  'length' => 'Length<br /><small>days/hours</small>',
  'events' => 'Events',
);*/


// ----- INSTANCES.PHP -----
/*$GLOBALS['lang_instances'] = array
(
  'instances' => 'Instances',
  'total' => 'Total',
  'map' => 'Map',
  'level_min' => 'Minimum level',
  'level_max' => 'Min Level Heroic',
  'max_players' => 'Maximum players',
  'reset_delay' => 'Reset delay',
);*/


// ---- message.php ----
/*$GLOBALS['lang_message '] = array
(
  'main' => 'Send System Message/Global Notification',
  'announcement' => 'Announcement',
  'notification' => 'Notification',
  'both' => 'Both',
  'send' => 'Send',
  'empty_fields' => 'Empty Fields',
  'message_too_long' => 'Message too long',
  'system_message' => 'System Message',
  'global_notify' => 'Global Notify',
  'sent' => 'sent',
  'message_result' => 'Message Result',
);*/

?>