INSERT INTO `config_misc` VALUES ('QIV_Credits', '0');
INSERT INTO `config_misc` VALUES ('QIV_Gold', '0');
INSERT INTO `config_misc` VALUES ('UV_Credits', '0');
INSERT INTO `config_misc` VALUES ('UV_Gold', '0');
INSERT INTO `config_misc` VALUES ('Credits_Fractional', '0');
INSERT INTO `config_misc` VALUES ('Name_Change_Credits', '0');
INSERT INTO `config_misc` VALUES ('Race_Change_Credits', '0');
INSERT INTO `config_misc` VALUES ('Transfer_Credits', '0');
INSERT INTO `config_misc` VALUES ('Hearthstone_Credits', '0');